# Generated by Django 4.1.7 on 2023-02-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True)),
                ('pdf', models.FileField(upload_to='tbook/pdfs')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='tbook/covers')),
            ],
        ),
    ]
