# Generated by Django 4.1.7 on 2023-02-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0003_alter_tbook_cover_alter_tbook_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True)),
                ('pdf', models.FileField(upload_to='ebook/media/rbook/pdfs')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='ebook/media/rbook/covers')),
            ],
        ),
        migrations.AlterField(
            model_name='tbook',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='ebook/media/tbook/covers'),
        ),
        migrations.AlterField(
            model_name='tbook',
            name='pdf',
            field=models.FileField(upload_to='ebook/media/tbook/pdfs'),
        ),
    ]
