# Generated by Django 4.1.7 on 2023-03-07 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0006_quiz_alter_rbook_cover_alter_rbook_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
        migrations.DeleteModel(
            name='Deleterequest',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
